### ISSUE TITLE
cannot build tvm

### ISSUE THREAD

**Issue by ghost** [thongdk8/realtime-facereccpp#1]
Thank you for the repository.

I build llvm-6.0.0.src from source. I did the following:
mkdir build
cp cmake/config.cmake build
and changed the configuration like this:
set(USE_CUDA ON)
set(USE_LLVM "F:/soft/llvm-6.0.0.src/build/Release/bin/llvm-config.exe" ON)

Now I am building tvm with:
cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" ..

The build is successful but the Release/ folder is empty and when I am building tvm.sln with visual studio, I have this issue:
linker error: Cannot open tvm.lib
It cannot open the file, because it does not exist. The cmake is not created tvm.lib in Release folder. neither 
https://discuss.tvm.ai/t/unable-to-install-tvm-along-with-llvm-on-windows/414
or 
https://discuss.tvm.ai/t/resolved-cannot-open-input-file-release-tvm-lib/1636
did not help.

Please help. 

my os and system:
windows 10, win64 visual studio 2015 update 3, using cuda 8

**Comment by xiaoliumi** [comment]
I am in the same trouble with you. Do you get any progress on this problem?


PS D:\DeepLearning\tvm\build> cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_CONFIGURATION_TYPES="Release" -DLLVM_DIR=D:/DeepLearning/LLVM/build/lib/cmake/llvm ..
-- The C compiler identification is MSVC 19.16.27030.1
-- The CXX compiler identification is MSVC 19.16.27030.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build with RPC support...
-- Build with Graph runtime support...
-- VTA build is skipped in Windows..
-- Found CUDA_TOOLKIT_ROOT_DIR=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0
-- Found CUDA_CUDA_LIBRARY=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cuda.lib
-- Found CUDA_CUDART_LIBRARY=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudart.lib
-- Found CUDA_NVRTC_LIBRARY=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nvrtc.lib
-- Found CUDA_CUDNN_LIBRARY=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib
-- Found CUDA_CUBLAS_LIBRARY=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cublas.lib
-- Build with CUDA support
-- Link with static LLVM libraries
-- Found LLVM_INCLUDE_DIRS=D:/DeepLearning/LLVM/includeD:/DeepLearning/LLVM/build/include
-- Found LLVM_DEFINITIONS=-D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -DUNICODE -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-- Found TVM_LLVM_VERSION=80
-- Build with LLVM 8.0.0
-- Set TVM_LLVM_VERSION=80
-- Build with contrib.sort
-- Build with contrib.hybriddump
-- Configuring done
-- Generating done
-- Build files have been written to: D:/DeepLearning/tvm/build

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“Release\tvm.lib”	nnvm_compiler	D:\DeepLearning\tvm\build\LINK	1	
错误	C2065	“uint”: 未声明的标识符	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2146	语法错误: 缺少“;”(在标识符“i”的前面)	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2143	语法错误: 缺少“;”(在“=”的前面)	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2143	语法错误: 缺少“)”(在“=”的前面)	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2059	语法错误:“=”	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2065	“i”: 未声明的标识符	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2059	语法错误:“)”	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	723	
错误	C2065	“i”: 未声明的标识符	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	724	
错误	C2059	语法错误:“;”	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	724	
错误	C2065	“shape”: 未声明的标识符	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	727	
错误	C3536	“data”: 初始化之前无法使用	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	728	
错误	C2664	“tvm::runtime::Object tvm::runtime::Object::Tensor(const tvm::runtime::NDArray &)”: 无法将参数 1 从“int”转换为“const tvm::runtime::NDArray &”	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	728	
错误	C3536	“obj”: 初始化之前无法使用	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	729	
错误	C2664	“void tvm::runtime::vm::VirtualMachine::WriteRegister(tvm::runtime::vm::RegName,const tvm::runtime::Object &)”: 无法将参数 2 从“int”转换为“const tvm::runtime::Object &”	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	729	
错误	C2046	非法的 case	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	733	
错误	C2046	非法的 case	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	752	
错误	C2046	非法的 case	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	762	
错误	C2046	非法的 case	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	771	
错误	C2046	非法的 case	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	791	
错误	C2059	语法错误:“}”	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	812	
错误	C2143	语法错误: 缺少“;”(在“}”的前面)	tvm_runtime	D:\DeepLearning\tvm\src\runtime\vm\vm.cc	812	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\backend\graph_plan_memory.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\backend\graph_runtime_codegen.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\backend\interpreter.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\backend\vm\compiler.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\backend\vm\lambda_lift.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\ir\alpha_equal.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\ir\hash.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\device_annotation.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\gradient.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\mac_count.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\match_exhaustion.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	C2059	语法错误:“.” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	76	
错误	C2143	语法错误: 缺少“;”(在“}”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	76	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	77	
错误	C2146	语法错误: 缺少“;”(在标识符“aRep”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	77	
错误	C2065	“src_rep”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	77	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C2086	“const int SRC_REP_T”: 重定义 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C2146	语法错误: 缺少“;”(在标识符“aAbs”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C2065	“srcAbsMask”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C2086	“const int SRC_REP_T”: 重定义 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C2146	语法错误: 缺少“;”(在标识符“sign”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C2065	“srcSignMask”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	80	
错误	C2146	语法错误: 缺少“;”(在标识符“absResult”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	80	
错误	C2059	语法错误:“if” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	82	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	82	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	82	
错误	C2059	语法错误:“else” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	97	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	97	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	97	
错误	C2059	语法错误:“else” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	105	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	105	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	105	
错误	C2059	语法错误:“else” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	109	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	109	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	109	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2373	“DST_REP_T”: 重定义；不同的类型修饰符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2146	语法错误: 缺少“;”(在标识符“result”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2065	“absResult”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2065	“srcBits”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2065	“dstBits”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C3646	“f”: 未知重写说明符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C3646	“i”: 未知重写说明符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2059	语法错误:“.” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2143	语法错误: 缺少“;”(在“}”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2059	语法错误:“}” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2059	语法错误:“return” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	138	
错误	C2059	语法错误:“}” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	139	
错误	C2143	语法错误: 缺少“;”(在“}”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	139	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\HalideIR\src\tvm\node\node.h	237	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\simplify_inference.cc)	tvm	D:\DeepLearning\tvm\3rdparty\HalideIR\src\tvm\node\node.h	237	
错误	C2059	语法错误:“.” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	76	
错误	C2143	语法错误: 缺少“;”(在“}”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	76	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	77	
错误	C2146	语法错误: 缺少“;”(在标识符“aRep”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	77	
错误	C2065	“src_rep”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	77	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C2086	“const int SRC_REP_T”: 重定义 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C2146	语法错误: 缺少“;”(在标识符“aAbs”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C2065	“srcAbsMask”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	78	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C2086	“const int SRC_REP_T”: 重定义 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C2146	语法错误: 缺少“;”(在标识符“sign”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C2065	“srcSignMask”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	79	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	80	
错误	C2146	语法错误: 缺少“;”(在标识符“absResult”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	80	
错误	C2059	语法错误:“if” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	82	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	82	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	82	
错误	C2059	语法错误:“else” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	97	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	97	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	97	
错误	C2059	语法错误:“else” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	105	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	105	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	105	
错误	C2059	语法错误:“else” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	109	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	109	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	109	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2373	“DST_REP_T”: 重定义；不同的类型修饰符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2146	语法错误: 缺少“;”(在标识符“result”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2065	“absResult”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2065	“srcBits”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C2065	“dstBits”: 未声明的标识符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	136	
错误	C3646	“f”: 未知重写说明符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C4430	缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C3646	“i”: 未知重写说明符 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2059	语法错误:“.” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2143	语法错误: 缺少“;”(在“}”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2059	语法错误:“}” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	137	
错误	C2059	语法错误:“return” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	138	
错误	C2059	语法错误:“}” (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	139	
错误	C2143	语法错误: 缺少“;”(在“}”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\compiler-rt\builtin_fp16.h	139	
错误	C2143	语法错误: 缺少“;”(在“{”的前面) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\HalideIR\src\tvm\node\node.h	237	
错误	C2447	“{”: 缺少函数标题(是否是老式的形式表?) (编译源文件 D:\DeepLearning\tvm\src\relay\pass\quantize.cc)	tvm	D:\DeepLearning\tvm\3rdparty\HalideIR\src\tvm\node\node.h	237	
错误	C2375	“tvm::relay::Bind”: 重定义；不同的链接 (编译源文件 D:\DeepLearning\tvm\src\relay\pass\type_infer.cc)	tvm	D:\DeepLearning\tvm\include\tvm\relay\pass.h	456	
错误	LNK1181	无法打开输入文件“Release\tvm.lib”	tvm_topi	D:\DeepLearning\tvm\build\LINK	1

**Comment by ghost** [comment]
Nope...
The author is not explained enough what to do....

**Comment by thongdk8** [comment]
sorry about a late comment. Just follow as official document https://docs.tvm.ai/install/from_source.html#. Please note that LLVM 6.0 is highly recommended.

**Comment by thongdk8** [comment]
anyway, I think it's more convenient if you use docker or build on Linux-base OS
